circle.yml
web/package.json

This branch builds the docker container for the web ui and pushes it to https://hub.docker.com/r/kindlyops/complianceops/

Build web container

---

web/src/Main.elm
web/src/View/Home.elm

Drawer avatar

---

circle.yml
docker-compose.yml
marketing/Caddyfile
marketing/Dockerfile
marketing/config.toml
marketing/public/index.xml
marketing/public/sitemap.xml
marketing/vendor/linux/README.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kindlyops/mappamundi/10)

Marketing site

---

circle.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kindlyops/mappamundi/11)

Fix typo in docker push container name.

---

deploy/dev.sql
docker-compose.yml
web/elm-package.json
web/scripts/start.js
web/src/API.elm
web/src/Model.elm
web/src/Msg.elm
web/src/Regulation.elm
web/src/Update.elm
web/src/View/Home.elm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kindlyops/mappamundi/12)

initial GET api working without JWT

---

README.md
web/README.md
web/elm-package.json
web/src/Update.elm
web/src/View/Home.elm
web/src/View/Login.elm

@joelclermont I took a stab at the elm-mdl upgrade and it wasn't too bad (although as you will see the webUI we have is still very primitive.

Upgrade elm-mdl to 8.1.0

---

README.md
docker-compose.yml
keycloak/keycloak-add-user.json

This adds keycloak to the dev environment at http://localhost:8080/

Adding keycloak auth server.

---

README.md
circle.yml
k8s/webui-deployment.yaml

Rename complianceops container to havenweb

---

README.md
web/src/Model.elm
web/src/View/Home.elm
web/src/main.css

A few small tweaks to the documentation and styling while getting the app up and running.

Up and running

---

k8s/cloudformation-route53-dns.yaml
k8s/havenweb-service.yaml
k8s/webui-deployment.yaml

Deployed and running at https://app.havengrc.com

k8s definitions for deployment of havenwebui

---

README.md

Notes on how to deploy with kubernetes.

---

README.md
docker-compose.yml
web/Caddyfile-dev
web/config/webpack.config.dev.js
web/installrun.sh
web/scripts/start.js
web/src/index.js

This change gets rid of the hardcoded AUTH0 client ID, it is now read from a .env file in development.

No hardcoded clientid

---

README.md
docker-compose.yml
postgrest/config
swagger/index.html

Upgrade postgres to 4.0.0, add swagger-ui

---

TODO
web/src/index.html

I set the viewport and other meta options based on html5boilerplate. 
Also updated page title and meta description.
Before on mobile the text was tiny and zoomed out. Now it's "normal".

Adjust viewport for mobile

---

README.md

Add thanks badge.

---

.github/PULL_REQUEST_TEMPLATE.md

Tweaks the PR template to make it clear.

It's ok to delete stuff in the PR template.

---

Dockerfile
docker-compose.yml
sqitch/Dockerfile
web/Dockerfile-hotreload

Pull docker images via Artifactory proxy.

Pull docker images via Artifactory proxy.

---

web/bower.json
web/elm-package.json
web/src/Route.elm
web/src/State.elm
web/src/View/Home.elm
web/src/WebComponents/App.elm
web/src/WebComponents/Paper.elm
web/src/index.html

Working from example at
http://polymerelements.github.io/app-layout/templates/publishing/#/art/list
This will definitely need later refactoring, just baby steps toward getting a working nav drawer.

Beginnings of polymer based responsive nav.

---

docker-compose.yml
web/bower.json
web/src/Route.elm
web/src/State.elm
web/src/Types.elm
web/src/View/Home.elm
web/src/index.html

A bunch of cleanup. 
Working on getting our first paper form set up to be able to add some data to the database, styling and layout is still pretty rough but I want to be able to round-trip some data. If you manually put regulation records in the DB with `curl` it renders data on the screen, but we really need a working form to make this tolerable. Added paper-form, the form submission is not working yet

Regulations

---

web/src/View/Home.elm
web/src/main.scss

I set the bottom and left as % instead of px just so it's not *as* hard-coded. That can be changed though.

Logo is centered at bottom of drawer.

---

web/bower.json
web/package.json
web/src/View/Home.elm
web/src/index.html
web/src/main.scss

Following this - https://www.webcomponents.org/element/PolymerElements/paper-menu-button
There's no iron-selects in the content (apparently could cause an issue).
When I click the icon, it shows the "ripple" effect that shows it might work but then no menu.

User dropdown menu

---

.eslintrc.json
web/config/webpack.config.dev.js
web/package.json
web/scripts/start.js
web/src/Authentication.elm
web/src/index.js

Working on keeping login state synchronized via keycloak iframe.

Session status

---

web/bower.json
web/src/View/Home.elm
web/src/index.html
web/src/main.scss

User avatar image is up.
changed the menu dropdown icon to more closely match the mockup. 
I'm having a bit of trouble with what I like for the user menu visually. On mobile/responsive, the menu is (only partially) going off screen.

Initial work on user avatar

---

web/bower.json

Merging gravatar branch into user-avatar.

Merged with gravatar

---

keycloak/themes/haven/login/resources/css/haven.css
keycloak/themes/haven/login/theme.properties

Add sample theme css file.

---

keycloak/themes/haven/login/login.ftl
keycloak/themes/haven/login/resources/css/haven.css

h1 font-size was just too big for small screens. Fixed to have a different font-size below 768px.

Mobile responsive

---

docker-compose.yml
keycloak/configuration/standalone.xml
web/Caddyfile-dev
web/vendor/linux/LICENSES.txt
web/vendor/linux/README.txt

This is version upgrades for a bunch of the infrastructure components we use.
Also fixes ngrok compatibility so you can actually login now! This should make testing with real devices much easier, as well as demos.

Upgrade keycloak

---

keycloak/themes/haven/account/applications.ftl
keycloak/themes/haven/account/resources/css/haven.css
keycloak/themes/haven/account/sessions.ftl
keycloak/themes/haven/account/template.ftl
keycloak/themes/haven/account/theme.properties
keycloak/themes/haven/account/totp.ftl
keycloak/themes/haven/login/error.ftl
keycloak/themes/haven/login/info.ftl
keycloak/themes/haven/login/login-config-totp.ftl
keycloak/themes/haven/login/login-totp.ftl
keycloak/themes/haven/login/login.ftl
keycloak/themes/haven/login/resources/css/haven.css
keycloak/themes/haven/login/template.ftl
keycloak/themes/haven/login/template_2.ftl
keycloak/themes/haven/login/theme.properties

If OTP authentication is enabled, there were new login pages that appear. They needed to be designed with the Haven theme.

Login theme

---

webui/src/main.scss

Makes root full width. Fixing the whole page offset to left.

css change for login page

---

README.md
apitest/features/minimal.pdf
apitest/features/sqitch-files.feature
deploy/files.sql
revert/files.sql
sqitch.plan
verify/files.sql

it's not the best solution in the world, but for now store files in the DB backend using base64 encoding.

Store PDF files in the backend using base64 encoding.

---

README.md
docker-compose.yml

This removes tellform from project. 

removing tell form

---

.circleci/config.yml

fix docker image upload

---

.circleci/config.yml

Add the openshift client, authenticate to our openshift cluster, and import the havenweb image to the cluster.

Install openshift client

---

.circleci/config.yml

WIP
Adding building/publishing to docker repo.

adding support for build/publish/deploy havenapi service

---

.circleci/config.yml
CONTRIBUTING.md
docker-compose.yml
havenapi/Dockerfile
havenapi/actions/app.go
havenapi/actions/home.go
havenapi/actions/home_test.go
havenapi/database.yml
k8s/havenapi-deployment.yaml
k8s/havenapi-service.yaml
k8s/nginxdemo-deployment.yaml
keycloak/Dockerfile
keycloak/data/havendev-realm.json
keycloak/themes/haven/account/template.ftl
webui/Caddyfile
webui/Caddyfile-dev
webui/src/Comment/Rest.elm

This gives us a functioning deployment of havenapi inside OpenShift. healthcheck is running and successfully connecting to the DB, and secrets and keys are configured inside k8s.
Next step is exposing the api deployment as a Service that is reachable externally, this will likely require dealing with TLS and DNS.
@knmurphy I'd like you to review this PR with me to be sure that someone other than me knows how this was put together.
Some useful commands to know:
`oc get events`
`oc get deployments`
`oc get pods`
Also very useful to browse around the pods in the OpenShift web interface. The metrics, terminal, and logs tabs are incredibly useful.

Working Haven API deployment

---

docker-compose.yml
keycloak/Dockerfile
keycloak/configuration/standalone.xml
keycloak/themes/haven/account/account.ftl
keycloak/themes/haven/account/applications.ftl
keycloak/themes/haven/account/password.ftl
keycloak/themes/haven/account/sessions.ftl
keycloak/themes/haven/account/totp.ftl
keycloak/themes/haven/login/login.ftl
keycloak/themes/haven/login/register.ftl
webui/src/Keycloak.elm

The changes to the theme files are removing the html escaping since that is a change that was done in keycloak upstream https://github.com/keycloak/keycloak/commit/9083e5fe5cb5ba6b63042f759c74984e1d1a1a76#diff-5a73f9053c9cc723d775a27d9973bb80
Other changes to the urls in theme files are to correspond to changes made upstream.
In the user profile, id is renamed to email to match the data that keycloak is providing now.
standalone.xml was updated with new dependencies and configuration from upstream, and has our change merged to set the default theme to haven.

Upgrade to Keycloak 3.4.2 Final.

---

keycloak/DESIGN.md

Adding more documentation regarding multitenant design.

Add multitenant doc

---

.circleci/config.yml
README.md
k8s/havenweb-deployment.yaml
k8s/havenweb-service.yaml
webui/Dockerfile

Deploy havenweb container to OpenShift Online 3

Havenweb openshiftonline deployment

---

README.md
deploy/dev.sql
deploy/files.sql
havenapi/actions/app.go
havenapi/models/sql/queries.sql
keycloak/data/havendev-realm.json

Here are some of the changes to add the Group Membership client mapper named "org".

Refactor to grab org/group claim.

---

webui/Caddyfile-dev

This fixes the reverse proxy for comments api in local dev environment.

Correct the port used by api in dev.

---

README.md

We are adding this for BrowserStack open source project account so we can test various browsers using BrowserStack. 
Signed-off-by: Kevin N. Murphy knmurphy@users.noreply.github.com

adding browserstack logo

---

.circleci/config.yml
havenapi/Dockerfile
verify/dev.sql
verify/files.sql
verify/roles.sql

Major CI refactor, introduce CircleCI workflows.

---

chargebee-provider/src/main/java/org/kindlyops/providers/chargebee/ChargeBeeRegistration.java
keycloak/themes/haven/login/register.ftl

This adds working logging code and passes a `form.attribute` to the `registration.ftl` template (`${pageUrl}`)

Spi logging

---

chargebee-provider/.gitignore
chargebee-provider/pom.xml
chargebee-provider/src/main/java/org/kindlyops/providers/chargebee/ChargeBeeRegistration.java

Hi! @statik @knmurphy 
This is a WIP that is currently broken. Pushed it up so that maybe you could chime in and see whats up. The config section works now but when you hit the registration page and trigger the SPI we get a java.lang.NoClassDefFoundError error regarding com/chargebee/Environment. I'm sure its got something to do with jboss classpath business...but I could use some extra eyes to see if maybe its something obvious... 
Thanks!

Refactor to add chargebee api to the spi.

---

README.md

Document one approach to TLS with Let's Encrypt certbot and manual dns challenge. This assumes tls passthrough on the openshift/kubernetes cluster.

Document one approach to TLS.

---

.circleci/config.yml

Re-enabling continuous delivery from CircleCI
Look in CircleCI and see if it deployed to openshift ok.

Re-enable deployments.

---

.codeclimate.yml

Initial CodeClimate configuration.

---

README.md

Signed-off-by: David Streeter <dstreet26@users.noreply.github.com>

updating readme to include instructions if docker's localhost fails

---

webui/vendor/README.md

Signed-off-by: Elliot Murphy <statik@users.noreply.github.com>

Update caddy to have the route53 dns plugin enabled.

---

README.md

Additional notes on handling TLS certificate renewal.

updated notes on TLS cert renewal.

---

webui/src/Main.elm

Add url back to user Profile link.

Refactor to fix broken link for user profiles.

---

.circleci/config.yml

Trying a different openshift login URL, since we are getting a strange error from CircleCI during deploy currently.

Try a different openshift login url.

---

webui/src/Main.elm
webui/src/Page/Survey.elm
webui/src/Route.elm

Removed prototype text.
Fixes HAV-68

Refactor to remove text from survey menu item.

---

webui/src/Main.elm

removed dead links from navbar, moved user profile back into drawer

Removing dead links, fixes HAV-67

---

.circleci/config.yml
notify-slack

Signed-off-by: Elliot Murphy <statik@users.noreply.github.com>

Overhaul slack notifications to be less spammy

---

chargebee-provider/pom.xml
keycloak/Dockerfile

The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31573
- https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32043
- https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32044
- https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32111
Signed-off-by: Elliot Murphy <statik@users.noreply.github.com>

fix: chargebee-provider/pom.xml to reduce vulnerabilities

---

docker-compose.yml
k8s/keycloak-deployment.yaml
keycloak/Dockerfile

keycloak 4 changed all the environment variable names for configuring the databas

More keycloak 4.0 postgres config fixes.

---

.circleci/config.yml
keycloak/themes/haven/login/register.ftl

Fix the submit button on the registration form.

Fix registration

---

README.md
keycloak/data/havendev-realm.json

This enables the google identity provider in keycloak in the dev realm, configured only for localhost.

Identity provider google

---

README.md

update the readme instructions

Fix the readme.

---

README.md
docker-compose.yml

This adds a container running pgadmin4, handy for poking around in the database.

Adding pgadmin4.

---

webui/elm-package.json

this will be handy for processing some larger text chunks.

Add elm-markdown package

---

keycloak/data/havendev-realm.json
postgrest/config

Standardize default client role == member for havendev.
Clean up users attributes.
Adjust postgrest claim-key to read havendev client role to
find role to assume in postgrest.

Remove extraneous groups, attributes, and realm roles.

---

k8s/havenapi-deployment.yaml

Adding needed env vars to access keycloak admin api.
Issue #HAV-120
Adds needed environment variables to the deployment.

WIP: Expose new keycloak env vars in kubernetes HAV-120

---

README.md
docker-compose.yml
webui/Caddyfile
webui/Caddyfile-dev

This adds Zed Attack Proxy and provides a way to run the scanner locally.
Future integration that would be cool: integrate the scanner into the CircleCI pipeline so that scans are done in the pipeline before allowing a deployment.

Add Zed Attack Proxy for security scanning.

---

webui/Caddyfile
webui/Caddyfile-dev

CSP fixes for keycloak in safari

More adjustments to Content-Security-Policy

---

webui/Caddyfile

Fixing X-Frame-Options on production build

Fix X-Frame-Options

---

webui/Caddyfile
webui/Caddyfile-dev

fixing security headers for keycloak

keycloak needs unsafe-inline for the login-status iframe

---

.tmuxp.yaml
README.md

Provides a tmux project wrapper that automatically sets up log tailing panes and vim.

Added tmuxp project layout.

---

README.md
RMarkdown-worker/TODO
RMarkdown-worker/compilereport.sh
RMarkdown-worker/docker-build/Dockerfile
RMarkdown-worker/docker-build/README.md
RMarkdown-worker/docker-build/build-and-push.sh
RMarkdown-worker/docker-compose.yml
docker-compose.yml

Some initial building blocks for Faktory background job system. Adds the webui and scheduler component, no background worker running yet.

Faktory stage 1

---

webui/elm-package.json
webui/src/Data/RadarChart.elm
webui/src/Request/Survey.elm
webui/src/Route.elm

This will help with the elm 0.19 upgrade

Get rid of elm-color-extra dependency

---

k8s/havenapi-deployment.yaml

Adjusts the KC_HOST and KC_PORT env vars to the correct
entries so that the api can connect.

WIP: Refactor to use proper host and port for keycloak.

---

flyway/sql/V19__registration_funnel_2.sql

We are implementing this API in havenapi since it needs
additional business logic.
Signed-off-by: Elliot Murphy <statik@users.noreply.github.com>

Remove the registration funnel API from PostgREST endpoint

---

README.md

Added documentation on running a migration with oc.

Document migration in production.

---

webui/src/Page/Survey.elm

Trying to do better about showing visuals for visual changes
Before
After

Only show the culture survey on survey page.

---

webui/src/Main.elm
webui/src/Route.elm

Get rid of the horrible # in our URLs

Path based routing

---

webui/src/Main.elm

put a container class around views that are rendered when logged out

Wrap outside views

---

flyway/sql/V19__registration_funnel_1_drop_view.sql

Removed duplicate migration.
Looks like I created a duplicate migration in the branch HAV-133 that was already in master. 

Fix for flyway error.

---

.circleci/config.yml
havenapi/keycloak/keycloak.go
havenapi/keycloak/keycloak_test.go
havenapi/vendor/github.com/contribsys/faktory/LICENSE
havenapi/vendor/github.com/contribsys/faktory/client/LICENSE
havenapi/vendor/github.com/contribsys/faktory/client/client.go
havenapi/vendor/github.com/contribsys/faktory/client/faktory.go
havenapi/vendor/github.com/contribsys/faktory/client/job.go
havenapi/vendor/github.com/contribsys/faktory/client/package.go
havenapi/vendor/github.com/contribsys/faktory_worker_go/.appveyor.yml
havenapi/vendor/github.com/contribsys/faktory_worker_go/.gitignore
havenapi/vendor/github.com/contribsys/faktory_worker_go/LICENSE
havenapi/vendor/github.com/contribsys/faktory_worker_go/Makefile
havenapi/vendor/github.com/contribsys/faktory_worker_go/README.md
havenapi/vendor/github.com/contribsys/faktory_worker_go/log.go
havenapi/vendor/github.com/contribsys/faktory_worker_go/pool.go
havenapi/vendor/github.com/contribsys/faktory_worker_go/runner.go
havenapi/vendor/github.com/contribsys/faktory_worker_go/runner_unix.go
havenapi/vendor/github.com/contribsys/faktory_worker_go/runner_windows.go
havenapi/vendor/github.com/contribsys/faktory_worker_go/types.go

This PR will eventually allow us to send emails when a user is created.
Issue #HAV-137

Send a confirmation email with buffalo background worker at registration funnel

---

havenapi/actions/registration_funnel.go
webui/Caddyfile
webui/Caddyfile-dev
webui/src/Data/Registration.elm
webui/src/Data/Survey.elm
webui/src/Main.elm
webui/src/Page/Survey.elm
webui/src/Request/Registration.elm

Now adds an email entry box if the user
is not logged in.
Issue #HAV-102

WIP: Implement post-survey registration

---

k8s/worker-deployment.yaml
worker/Dockerfile

* remove an unused secretVolume mount
* fix a space in the Docker build that might be causing a permissions error when running the container in an openshift pod

Fix worker configuration

---

.circleci/config.yml

less duplicated configuration for the slack notifications

Use new CircleCI commands to reduce duplication.

---

k8s/havenapi-deployment.yaml
k8s/worker-deployment.yaml

Fixes all the woes of deployment.

Fix faktory url deployment and worker db errors

---

webui/src/Page/Survey.elm

simplify survey navigation buttons per HAV-73

Less navigation buttons

---

havenapi/keycloak/keycloak.go
keycloak/themes/haven/email/html/email-test.ftl
keycloak/themes/haven/email/html/email-verification-with-code.ftl
keycloak/themes/haven/email/html/email-verification.ftl
keycloak/themes/haven/email/html/event-login_error.ftl
keycloak/themes/haven/email/html/event-remove_totp.ftl
keycloak/themes/haven/email/html/event-update_password.ftl
keycloak/themes/haven/email/html/event-update_totp.ftl
keycloak/themes/haven/email/html/executeActions.ftl
keycloak/themes/haven/email/html/identity-provider-link.ftl
keycloak/themes/haven/email/html/password-reset.ftl
keycloak/themes/haven/email/messages/messages_en.properties
keycloak/themes/haven/email/text/email-test.ftl
keycloak/themes/haven/email/text/email-verification-with-code.ftl
keycloak/themes/haven/email/text/email-verification.ftl
keycloak/themes/haven/email/text/event-login_error.ftl
keycloak/themes/haven/email/text/event-remove_totp.ftl
keycloak/themes/haven/email/text/event-update_password.ftl
keycloak/themes/haven/email/text/event-update_totp.ftl
keycloak/themes/haven/email/text/executeActions.ftl
keycloak/themes/haven/email/text/identity-provider-link.ftl
keycloak/themes/haven/email/text/password-reset.ftl

Sets up a haven email theme (based on the base theme).

Add email theme.

---

keycloak-service-providers/src/main/java/org/kindlyops/providers/rest/HavenRestResource.java

merging an experiment that didn't work for reference.

Try grabbing server URI

---

README.md
docker-compose.yml

Using this domain name trick will enable us to resolve some of the troublesome issue with keycloak and look much nicer!

Make dev.havengrc.com work instead of localhost:2015

---

unleash/index.js

remove imports from non-existent files.

Fix unleash crash

---

havenapi/models/sql/queries.sql

using a formatting tool seems like a nice idea.

Format SQL with sqlfum.pt

---

webui/src/Page/Landing.elm
webui/src/Views/SurveyCard.elm

Move the test animation out of the way, instead of being on /survey/ it is now on /l/

Move lottie test animation to /l/ landing page

---

keycloak/themes/haven/account/account.ftl
keycloak/themes/haven/account/federatedIdentity.ftl
keycloak/themes/haven/account/password.ftl
keycloak/themes/haven/account/resources/css/haven.css
keycloak/themes/haven/account/sessions.ftl
keycloak/themes/haven/account/totp.ftl
keycloak/themes/haven/login/login.ftl
keycloak/themes/haven/login/register.ftl
keycloak/themes/haven/login/resources/css/haven.css
keycloak/themes/haven/login/template_2.ftl

Overall visual improvements on keycloak pages

---

webui/src/Data/Survey.elm
webui/src/Main.elm
webui/src/Page/Comments.elm
webui/src/Page/Dashboard.elm
webui/src/Page/Errors.elm
webui/src/Page/Survey.elm
webui/src/Page/SurveyResponses.elm
webui/src/Ports.elm
webui/src/index.js

from child pages. Search for -- TODO refactor

Refactor snackbar handling to be pure Elm, no ports

---

README.md

trying ways to condense the readme on github

use collapsing details tag in README.

---

havenapi/keycloak/keycloak.go

This fixes a bug that prevents the user from
logging in for the first time due to missing
attributes. It also uses the first portion of the email address
as the placeholder for first name.
Complete a survey and attempt to login after the email steps.

Fixes a new user login bug

---

keycloak-service-providers/pom.xml
keycloak/Dockerfile
keycloak/configuration/standalone.xml
keycloak/data/havendev-realm.json

Refactor to upgrade keycloak

---

webui/src/Main.elm

Some code I had laying around, this makes clicking on the profile link actually force a page load rather than just changing the URL (because elm thought it was an internal page).

Fix navigation to profile page.

---

keycloak-service-providers/magic-link/README.md
keycloak-service-providers/magic-link/pom.xml
keycloak-service-providers/magic-link/src/main/java/org/kindlyops/auth/magic/MagicLinkFormAuthenticator.java
keycloak-service-providers/magic-link/src/main/java/org/kindlyops/auth/magic/MagicLinkFormAuthenticatorFactory.java
keycloak-service-providers/magic-link/src/main/resources/META-INF/jboss-deployment-structure.xml
keycloak-service-providers/magic-link/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
keycloak-service-providers/magic-link/src/main/resources/theme-resources/templates/login-email-only.ftl
keycloak-service-providers/magic-link/src/main/resources/theme-resources/templates/view-email.ftl
keycloak/Dockerfile
keycloak/data/havendev-realm.json
keycloak/themes/haven/login/login.ftl

This PR will add magic link abilities. 😄
Issue #HAV-151
Adds the magic link for keycloak 6
Supersedes #302

Refactor to add magic link

---

docker-compose.yml

Remove cadvisor to smooth out windows dev experience

---

havenapi/Dockerfile

2019/05/17 17:59:36 stat /go/src/github.com/kindlyops/havengrc/havenapi/models/sql/queries.sql: no such file o

Trying to fix packr file not found after buffalo upgrade

---

.circleci/config.yml
TODO
docker-compose.yml
gatekeeper/Dockerfile
gatekeeper/gatekeeper.yaml
havenapi/go.mod
havenapi/go.sum
unleash/index.js
webui/Caddyfile-dev
webui/Dockerfile-cypress
webui/Dockerfile-hotreload

This adds a bunch of building blocks for the switch from keycloak.js to keycloak-gatekeeper for authentication on our front end SPA.

Prep work for keycloak-gatekeeper

---

k8s/gatekeeper-deployment.yaml
k8s/havenweb-service.yaml
webui/src/Authentication.elm

Don't hardcode login button to dev.havengrc.com

Fix some gatekeeper config and login button for staging

---

gatekeeper/config/gatekeeper.tmpl

Forcing X-Forwarded-Proto header

---

flyway/sql/V28__no_anonymous_on_registration_funnel_1.sql
gatekeeper/config/gatekeeper.tmpl
webui/Caddyfile
webui/Caddyfile-dev
webui/src/Page/Reports.elm

Hi @statik !
So here is what I have so far with downloading the generated reports. This uses the RPC to grab the file for download.

Refactor to allow download of generated report

---

webui/Caddyfile
webui/Caddyfile-dev
webui/src/Main.elm
webui/src/Page/Dashboard.elm
webui/src/Page/Reports.elm

Issue #HAV-266
Hi @statik ! This PR will add the dashboardView that will allow users to download their latest reports right away.
##

Refactor to add new dashboardView for reports

---

worker/main.go

Hi @statik!
This will fix an off by one error that was occurring in our csv creation that caused the first question to not be displayed in the chart.
Issue #HAV-113

Refactor to fix bug in pptx output

---

webui/config/webpack.config.prod.js
webui/package-lock.json
webui/package.json

Rather than upgrading uglifyjs plugin, switch to terser to match what webpack is recommending for minification.

Switch from uglifyjs to terser for minification.

---

webui/package-lock.json
webui/package.json

npm update --depth=9999 cosmiconfig

Update js-yaml for security vuln.

---

webui/src/Page/Survey.elm
webui/src/main.scss

Also cleaned up margins causing pages to not be correct width.

Updated UI on the results page

---

havenapi/actions/app.go
havenapi/actions/surveys.go
havenapi/go.sum
webui/Caddyfile
webui/Caddyfile-dev
webui/src/Page/Survey.elm
worker/main.go

This will handle saving survey responses for logged in users. 
Issue #HAV-227

Adding new surveys api in gobuffalo

---

webui/src/Main.elm
webui/src/Page/Survey.elm

Displays the vega chart for logged in users and
checks for new reports when the user visits the
dashboard.

Refactor for logged in chart and get reports

---

webui/src/Page/Home.elm
webui/src/main.scss

TODO: button inside navbar is not working correctly

Navbar changes from Lauren.

---

webui/src/Page/Home.elm

Changed form to div and it magically works! No reason we need to use form at the moment anyways.

Form doesn't work / Div does

---

webui/elm.json
webui/src/Authentication.elm
webui/src/Main.elm
webui/src/Page/Reports.elm
webui/src/Utils.elm

Now tracking current time in authModel so that we can use it for relative formatting of dates ("a few minutes ago")

Add fancy formatting of report dates

---

k8s/api-deployment.yaml
k8s/havenapi-deployment.yaml
k8s/keycloak-deployment.yaml

Running into jwt issues in the new deployment due to some missing env var changes

Refactor to fix new deployment for www

---

webui/Caddyfile
webui/Caddyfile-dev
webui/src/Page/Home.elm
webui/src/index.js

Issue #HAV-277
Adds links for policies. Currently iframes.

Refactor to add iubenda links

---

webui/Caddyfile

Hi @statik  I think this might fix the issue we have been seeing.

Fix for proxy not terminating properly

---

worker/Dockerfile

Hi! @statik 
This should add the needed files and folder we needed in production.

Add needed files to container

---

keycloak-service-providers/magic-link/src/main/java/org/kindlyops/auth/magic/MagicLinkFormAuthenticator.java
keycloak-service-providers/magic-link/src/main/resources/theme-resources/templates/view-email.ftl
keycloak/themes/haven/login/template.ftl

Hi! This will now not provide and error to the user if they enter an invalid email. It also makes some needed tweaks to the templates.
Issue #HAV-280

Refactor to always display email sent msg

---

gatekeeper/config/gatekeeper.tmpl
webui/Caddyfile
webui/Caddyfile-dev
webui/public/index.html
webui/src/Main.elm
webui/src/Page/Cookie.elm
webui/src/Page/Home.elm
webui/src/Page/Survey.elm
webui/src/Page/Terms.elm
webui/src/Route.elm

Also refactor terms and privacy links.
/privacy, /terms, and /cookie are all their own dedicated pages on our site now. privacy and cookie both load the policies remotely from iubenda.

Add cookie policy page.

---

webui/elm.json
webui/src/Main.elm
webui/src/Page/Survey.elm

Now have ability to restart the survey after completing.
Fixed up message at end of survey to explain that report
will be on dashboard.
Fix vega rendering when navigating away from survey and back.

Bunch of survey completion cleanup.

---

webui/src/Page/Home.elm

You can keep it if you want, but I took it out.

Remove Lorem ipsum text

---

webui/src/Page/Home.elm

Hi! Just noticed a small typo so i thought i'd push a fix. :D 

Fix for typo

---

webui/src/Main.elm

Was a little over-eager when adding animations. This makes it so navigation when not authenticated works again (survey, terms, etc).

Fix navigation to survey when logged out.

---

apitest/features/sqitch-jwt.feature
flyway/sql/V31__alter_comments_id.sql
havenapi/actions/app.go
havenapi/actions/comments.go
havenapi/go.mod
havenapi/models/comment.go
webui/Caddyfile
webui/Caddyfile-dev
webui/src/Data/Comment.elm
webui/src/Page/Comments.elm

This will move the comments api to havenapi.
Issue #HAV-304

Move comments to havenapi

---

webui/src/main.scss

Removed flex and hard-coded heights

Fix question height

---

.circleci/config.yml
README.md
docker-compose.admin.yml
k8s/keycloak-deployment.yaml
k8s/keycloak-service.yaml
test
webui/Caddyfile
webui/Dockerfile
webui/Dockerfile-cypress
webui/cypress-ci.json
webui/cypress/Caddyfile.tmpl
webui/cypress/entrypoint.sh
webui/package-lock.json
webui/package.json

This is work on getting cypress running again.

Re-enable cypress tests

---

k8s/havenweb-deployment.yaml
k8s/havenweb-service.yaml

Correcting ports

---

k8s/gatekeeper-deployment.yaml

another port

---

apitest/features/sqitch-nojwt.feature
flyway/sql/V32__alter_ipsative_surveys_id.sql
flyway/sql/V33__alter_likert_surveys_id.sql
havenapi/actions/app.go
havenapi/actions/surveys.go
havenapi/models/surveys.go
webui/Caddyfile
webui/Caddyfile-dev
webui/src/Data/Survey.elm
webui/src/Page/Survey.elm

Issue #HAV-306
For now we will move the surveys to havenapi even though they dont do much.

Refactor to move surveys to havenapi

---

dc
dca
dump-token

Also better dependency checking/error messages.
Now using the step crypto helper instead of manual
decoding the token, which solves the base64
padding issues we were hitting with formatting a
decoded token for inspection.

More resilient JWT decoding in dev tools

---

.circleci/config.yml
k8s/gatekeeper-deployment.yaml
k8s/havenapi-deployment.yaml
k8s/havenweb-deployment.yaml
k8s/keycloak-deployment.yaml
report-changed-services
webui/README.md

A helper script to parse out the changes made in a branch so that we can do partial deployments rather than deploy all services for every change.

Report changed services

---

.circleci/config.yml
k8s/keycloak-deployment.yaml
report-changed-services

Don't push docker image versions that don't have changes.
Also includes a fix for the keycloak liveness probe.

Fix keycloak liveness probe

---

.circleci/config.yml
report-changed-services

Fix bugs with how we choose the latest container tag for each service.

Fix service version

---

.circleci/config.yml
dc
dca
e2e-tests-cleanup.sh
e2e-tests.sh
gatekeeper/entrypoint.sh
report-changed-services

An older branch to try and track down test failures.

Trying to track down test failures.

---

docker-compose.admin.yml
webui/cypress/integration/login_spec.js

Issue #HAV-320
This will now test creating and retrieving the magiclink from the email sent to the user and then using the link and logging in.

Adds a test for the magiclink
