- .gitignore
- web/Caddyfile
- web/config/webpack.config.dev.js
- web/config/webpack.config.prod.js
- web/docker-compose.yml
- web/src/index.js
The Auth0 client secret is now hardcoded in dev env
only. In a container environment Caddy will template
the env variable AUTH0_CLIENT_SECRET into the js file
when serving it. This allows us to configure the Auth0
secret for production deployments in kubernetes.
A future enhancement would be to make the dev secret
configurable as well via a .env in the root of this project
so that it's possible for other orgs to run this
against their own auth0 account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kindlyops/mappamundi/6)
> Auth0 client secret configurable in Container

- README.md
- docker-compose.yml
This runs the server, but doesn't yet have a way to
run setup.js to create the tellform accounts.
> Run tellform server in dev environment

- k8s/README.md
- k8s/webui-deployment.yaml
I've deployed this change to kubernetes already, and made a tweak to the Auth0 clients to configure app.havengrc.com as allowed. This means login now works for https://app.havengrc.com!
This works because the Caddy server is templating the generated JS, and injecting AUTH0_CLIENT_ID into the code at runtime by reading from the container environment. The container gets the value from the ConfigMap that is managed in kubernetes.
We'll need the same mechanism for keycloak and other things, this is the first example of getting it working end to end.
> Add configmaps for injecting config into webui code.

- .gitignore
- docker-compose.yml
This pins PostgREST to 4.0.0 now that Joe made us a version tag.
Also upgrades PosgreSQL from 9.5 to 9.6.2, and adds a persistent
data volume to store postgres data so that it will survive even if you
run `docker-compose down` and then `docker-compose up`.
> Postgres enhancements

- web/src/API.elm
- web/src/index.html
This needs to be changed to some sort of API_BASE_URL configuration option, but for now just fixing the hardcoded port number.
> Fix the API port for dev.

- web/.npmrc
This changes the build for the webui container to pull from our project Artifactory server so that npm modules are cached there.
> Use artifactory to cache npm modules.

- README.md
- web/.gitignore
- web/README.md
- web/bower.json
- web/elm-package.json
- web/installrun.sh
- web/package.json
- web/src/State.elm
- web/src/Types.elm
- web/src/View/Home.elm
- web/src/View/Login.elm
- web/src/index.html
- web/src/index.js
This removes elm-mdl from the app and switches to using webcomponents and the polymer implementations of Material Design elements.
At application boot time, bower is run after npm and before webpack to install the polymer components based on what is listed in bower.json.
The index.html is adjusted to add the webcomponents polyfill and to add the html imports for some common polymer components.
All the elm-mdl code is removed, and the old elm-mdl layout on the interior page is commented out for temporary reference.
The login and logout buttons still work, and are now paper-button tags using the paper-button component.
> Drop elm-mdl, start adding polymer.

- README.md
I wanted to add the extra line break to avoid any confusion that the next line "create .env" would be just for the Windows people too.
> Added assistance to the folks who use Windows.

- web/elm-package.json
- web/src/View/Home.elm
This swaps out the user image to pull from gravatar.com, using an elm library to generate the md5 hash of the user email address in order to generate the gravatar url.
This PR is targeted to merge into @laurencaitlan user-avatar branch, as it builds on the excellent work there.
> Pull avatar from gravatar.com

- docker-compose.yml
- keycloak/configuration/standalone.xml
- keycloak/themes/haven/account/theme.properties
- keycloak/themes/haven/admin/theme.properties
- keycloak/themes/haven/login/theme.properties
- keycloak/themes/haven/welcome/index.ftl
- keycloak/themes/haven/welcome/theme.properties
- web/src/index.js
Adding custom keycloak themes.
Custom standalone.xml disables theme caching and changes the welcome (keycloak /auth page) theme.
Docker compose changes publish custom haven theme directory to keycloak server.
Theme for the haven realm must be manually configured via the keycloack admin console, need to figure out how to automate this theme selection. Once that is done, we should be ready to actually write the CSS for the themes.
> Custom Keycloak themes

- .gitignore
- README.md
- docker-compose.yml
This makes it easy to handle email in dev. MailHog is a special
SMTP server that runs in dev and displays emails in a web UI
running on port 8025 instead of delivering them. Optionally you
can then release emails out to a real 3rd party SMTP server
For example, here is a screenshot of MailHog displaying the verification email from KeyCloak after I registered a new user.
> Add mailhog service for trapping emails in dev.

- README.md
- docker-compose.yml
- keycloak/data/havendev-realm.json
Now down to 2 simple commands.
docker-compose run start_dependencies
docker-compose up
These commands take care of the SMTP configuration, the
Keycloak realm import, the theme configuration, and running
the SQL migrations.
It should be possible to remove the first command by upgrading
to docker-compose 3 and adding healthchecks.
> Radical simplification of startup configuration.

- webui/src/Ports.elm
- webui/src/State.elm
- webui/src/Types.elm
- webui/src/View/Home.elm
- webui/src/index.js
This introduces the material design snackbar, which the way to show a message notification for example a network error - similar to a rails/bootstrap flash message. The styling may need to be adjusted but seems pretty decent to start with.
There is an error button on the dashboard page that will display a fake error, and the HTTP ajax requests are now wired up to display error messages in the UI. The most common time this happens right now is if you try to post a comment on the comments page after being logged for more than 5 minutes. The JWT token expires, and you get 401 access denied from the API call.
You can see the snackbar at the bottom of the screenshot, it animates back out after a brief delay.
> Error message snackbar

- webui/src/Ports.elm
- webui/src/State.elm
- webui/src/Types.elm
- webui/src/View/Home.elm
- webui/src/index.js
- webui/src/main.scss
I made some revisions to the colors based on guidance in the material design color system about when to use the primary theme color and when to use secondary. The mockups from Hiromi were using the secondary or accent color for the header, and the color system is intended so that the primary color is used for the header and the main action button can then use the secondary color or a lighter/darker version of the primary. https://material.io/guidelines/style/color.html#color-color-system. 
Aaron created this color palette for us:
We may end up wanting to do a revision of the color palette based on https://material.io/guidelines/style/color.html#color-color-palette
I think this change is more calm and confident.
> Tweak colors

- webui/src/index.js
Runtime exceptions! I wish we didn't need javascript to trigger the MDC animations, but I guess thats the price we have to pay.
> Fix snackbar crash when logged out.

- webui/src/Authentication.elm
- webui/src/Comment/Rest.elm
- webui/src/Ports.elm
- webui/src/State.elm
- webui/src/index.js
This organizes and refactors some of the authentication code.
A crash was fixed with snackbar.
Keycloak has both refresh tokens and access tokens. Refresh tokens are kept by keycloak.js. Access tokens are used to send to the backend service. Refresh tokens expire quickly (5 min) and so we were being left in a state of being logged in but with an invalid token. Refresh is now hooked up to correctly exchange the token when it expires, and pass the fresh token in to the Elm model.
Refresh token activity will cause the session to appear active to keycloak, so it prevents the session timeout from being reached even when the page is idle. I need to adjust refresh token so it is only done when the user is active (perhaps only when we are about to make an API call).
The keycloak session status …
> Authentication cleanup, token refresh, session expiry, single sign-out

- apitest/features/sqitch-jwt.feature
- deploy/dev.sql
- webui/src/Comment/Rest.elm
- webui/src/Comment/Types.elm
- webui/src/View/Home.elm
Users can change their email addresses over time. When attributing records to a user we need to use a more stable user ID. Keycloak identifies each user with a stable uuid, and this is exposed as the sub claim in the JWT, and as the `id` in the profile. This PR adjusts the database code to store the stable user id along with the email. In the future we should probably maintain a separate uuid -> user profile table, or gather this info from the keycloak API if we end up doing graphql.
> Record stable keycloak user ID in addition to email.

- .circleci/config.yml
- k8s/keycloak-deployment.yaml
- k8s/keycloak-service.yaml
The build process was accidentally tagging the sqitch docker image as havenapi and then deploying the wrong thing.
> Fix havenapi images

- .circleci/config.yml
- docker-compose.yml
- k8s/api-deployment.yaml
- k8s/api-service.yaml
- postgrest/Dockerfile
- postgrest/config
These are the spec files required for deployment to OpenShift Online. The docker image has moved from upstream postgrest to kindlyops registry because of Audience claim code that is not in master upstream yet. 
`postgrest/dockerfile` provides defaults for the postgrest config and `api-deployment.yaml` overrides most of those.
> Postgrest openshift online deployment & service spec

- .circleci/config.yml
- webui/Caddyfile
This adjusts the proxy settings to match the way we have the api service configured in production.
> Adjust the Caddy proxy backend api port to match production.

- README.md
- flyway/sql/V2__dev_comments.sql
- flyway/sql/V3__file_uploads.sql
- webui/src/State.elm
When we migrated to using flyway for migrations, the uuid
extension started getting installed into the mappa schema
instead of the public schema.
https://stackoverflow.com/a/39751566
After this change is deployed the staging database will need to be dropped (cleaned) and re-built, and then posting comments should work again.
> HAV-33 #close fixed 404 bug on inserts.

- dump-token
- get-token
This adds two command line utilities that make it easy to grab a JWT token for use with curl and to decode and pretty-print the payload of claims contained in a JWT token. This should make it easier to interactively work with keycloak as we set custom attributes etc.
> Add utilities for getting and decoding JWT tokens.

- chargebee-provider/.gitignore
- chargebee-provider/pom.xml
- chargebee-provider/src/main/java/org/kindlyops/providers/chargebee/ChargeBeeRegistration.java
- chargebee-provider/src/main/resources/META-INF/MANIFEST.MF
- chargebee-provider/src/main/resources/META-INF/services/org.keycloak.authentication.FormActionFactory
- keycloak/themes/haven/account/account.ftl
- keycloak/themes/haven/login/register.ftl
Hi @statik 
This adds the organization to the registration page and also the account page. Along with the base of the provider that will handle organizational verification and assignment to a new chargebee customer id. 
**TODO** 
Right now you need to manually add the `organization` attribute to the parent group or directly to a user for testing.
Perhaps we should rename the chargebee-provider to something more like organization-management-provider since we could possibly handle other tasks involved with organization creation/modification.
I assume we want to handle group creation here if it passes verification? Thoughts on this?
> Example org changes

- keycloak/Dockerfile
This incorporates the custom keycloak SPI into the docker build process.
I've been doing
$ alias dc='docker-compose'
$ dc build keycloak && dc up keycloak
Then I can CTRL-C and re-run after changing source code.
> Build and install our custom keycloak SPI

- keycloak/data/havendev-realm.json
This makes it so that both user1 and user2 in the dev setup have email addresses on their user profile.
We will need to revisit the user signup flow and what attributes we want to guarantee in keycloak, but for now this puts user2 in a usable state when doing a fresh setup.
> Add email address to user2 profile in dev.

- webui/Caddyfile-dev
Newer caddy releases use a different syntax for event handling, update to work with the newer version of caddy that we are using.
> Fix caddy syntax to work with newer version.

- flyway/Dockerfile
While investigating the errors I was getting running flyway, I noticed there have been several point releases. Update to use the current stable release.
> Grab a newer point release of flyway.

- .circleci/config.yml
Remove manual approval step in CircleCI to streamline deploys.
I like manual approval but without getting prompted in slack it's frustrating to realize the deploy is waiting for approval.
> Remove the manual approval before deploys.

- keycloak/Dockerfile
in staging keycloak login is broken, there is no havendev realm.
looking at the logs, it seems like the keycloak container is using H2 instead of connecting to postgres. this change seems like it might help connect to postgres.
> Trying to fix keycloak using H2 instead of postgres in prod

- postgrest/Dockerfile
The new version Postgrest was failing the jwt validation so we are reverting commit 461b57edf2156645d4bbb769191877db5772ced2. 
We will have to investigate further as to why exactly it is failing but this should correct the issues we were seeing.
> Revert "update to postgrest 5"

- keycloak/data/havendev-realm.json
When registering a new account via google IdP, don't require email account verification.
> Don't require email verification when logging in from google.

- keycloak/data/havendev-realm.json
This enables the GitHub identity provider in the dev realm (localhost only).
> Enable GitHub IdP in dev realm (localhost only)

- .circleci/config.yml
- docker-compose.yml
- keycloak/Dockerfile
Some of the permissions tweaks are already included in this
upstream image, simplifies our Dockerfile and also makes
it easier for my bazel experiments.
Need to test in staging to confirm this image runs ok in the openshift environment. Works fine in local dev under docker-compose.
> Switch to the keycloak-openshift base image.

- apitest/features/sqitch-jwt.feature
- apitest/features/sqitch-nojwt.feature
- apitest/features/step_definitions/steps.rb
- flyway/sql/V15__likert_questions.sql
- postgrest/Dockerfile
Allows for anonymous read only access to likert questions.
Update to postgrest5.
Issue #HAV-94
`docker-compose run apitest`
> Refactor to grant anonymous read only for likert.

- webui/Caddyfile
building block for switching from hash-based routing to
path-based routing.
> Send SPA instead of 404 for non-root page loads.

- WORKSPACE
- keycloak/Dockerfile
- keycloak/configuration/standalone.xml
This updates from Keycloak 4.0 to 4.3. Release notes here:
https://www.keycloak.org/docs/latest/release_notes/index.html
> Keycloak 4.3.0.Final
Hostname SPI
The hostname SPI introduces a more flexible way to configure the hostname for Keycloak. There are two built-in providers. The first is request, which uses the request headers to determine the hostname. The second is fixed, which allows configuring a fixed hostname. The latter makes sure that only valid hostnames can be used and also allows internal applications to invoke Keycloak through an alternative URL.
> For more details refer to the threat mitigation section in the Server Administration Guide.
> X509 Client Authenticator
The newly added Client Authenticator uses X509 Client Certificates and Mutual TLS to secure a connection from …
> Upgrade to Keycloak 4.3.0-Final

- webui/Caddyfile
- webui/Caddyfile-dev
The previous security headers were much too strict and broke things.
Revised to:
* allow loading fonts from data attributes
* allow loading images from data attributes
* allow loading images from www.gravatar.com
* allow loading frames from sameorigin (for keycloak login status hidden iframe)
> Adjust security headers to fix breakages.

- webui/package.json
We don't need to re-run npm install every time the container
starts. Instead, developers need to rebuild the container
when adding/removing packages. This will greatly speed up
startup during normal development and reduce the amount of
network traffic from repeated npm installs.
> Speed up start of webui container.

- webui/src/Page/Survey.elm
- webui/src/Page/SurveyResponses.elm
This change removes the second unused group.
Issue #HAV-71
When we conduct the SCDS diagnostic survey during an assessment, the survey is about the current state, not about the state of multiple groups.
> Refactor to change SCDS survey to 1 group.

- webui/src/Page/Survey.elm
Tiny steps towards streamlining the surveys.
The SurveyInstructions page at the beginning of a survey is an extra click that is
unneeded. Jump right into the survey and show the instructions
on every page of the survey.
Styling is still needed, this is just the structural change.
> Don't show the SurveyInstructions page.

- webui/src/Page/Survey.elm
Justifies the survey control buttons 
* [ x] For visual changes, I've attached before and after screenshots
> justifies controls at bottom of survey page

- havenapi/actions/registration_funnel.go
- havenapi/actions/registration_funnel_test.go
Now sends slack notification when a user inits
a registration with the funnel. Includes a test.
The SLACK_WEBHOOK env var must be set with the
webhook URL of your choice.
Issue #HAV-149
> Refactor to add slack notification.

- .circleci/config.yml
It seems like jfrog has trouble with larger images,
bypassing for now and having the k8s deployment pull directly from docker hub to remove one more source of troubleshooting.
> Don't deploy worker image via jfrog

- webui/Caddyfile
- webui/Caddyfile-dev
- webui/src/Page/Survey.elm
Disable the next button until all points are allocated for the current question.
> Conditional next

- webui/src/index.js
trying a workaround from https://github.com/airbnb/lottie-web/issues/914 to see if it makes lottie animation work on mobile safari.
> try setlocation href workaround for safari mask

- docker-compose.yml
- k8s/worker-deployment.yaml
works around issue with proxy host in keycloak by sending
API traffic in via the front door.
> Adjust routing from worker to keycloak REST API.

- worker/Dockerfile
- worker/docker-build/build-and-push.sh
- worker/docker-compose.yml
This will eventually need to split into our own base image
for haven to allow the reporter toolchain to evolve
independently.
> Move over to worker-base to avoid size problems

- webui/public/index.html
- webui/src/Main.elm
- webui/src/index.js
This seems to work. 🤷‍♂️ 
It would be nicer to get rid of the JS port that is doing the class stuff for show/hide and move that into Elm.
> Try to get the error snackbar working

- flyway/sql/V24__ipsative_answers_add_category.sql
- webui/src/Data/Survey.elm
This change alows for usage of the answer
category column.
Issue #HAV-259
This allows for populating a new 'category' field in the elm answers data record to expose
it to the ui.
View the json with `http://localhost:2015/api/ipsative_data?survey_id=eq.$SOMESURVEYID`
> Expose answer category

- keycloak/themes/haven/login/login.ftl
Fixes the redirect_uri query string.
> Fix for redirect_uri

- docker-compose.yml
- webui/src/Page/Survey.elm
More improvements to survey slider UI logic, now correctly handles points remaining and doesn't allow exceeding available points.
There is still a bug where the sliders stop working as soon as points remaining goes to zero and the "Next" button activates. Going to merge anyway to share this incremental improvement.
> Survey points remaining

- webui/src/Page/Survey.elm
Fix survey slider logic to allow reducing points allocated after hitting max points. Previously the sliders would get "stuck" as soon as remaining points hit 0.
> Fix bug where range slider got stuck after max points

- keycloak-service-providers/magic-link/src/main/java/org/kindlyops/auth/magic/MagicLinkFormAuthenticator.java
This will now disable the terms and conditions check when using the magic link.
We will have to have to add a checkbox and appropriate wording for terms and conditions with the registration funnel.
> Refactor to disable terms with magic link

- .remarkrc
add configuration file for the markdown linting tool to reduce the markdown issues reported by Codacy.
> Configure remark-lint to be reasonable on Codacy

- gatekeeper/Caddyfile.tmpl
- k8s/gatekeeper-deployment.yaml
internal openid discovery is redirecting to https.
> work around keycloak redirects on internal network

- gatekeeper/config/gatekeeper.tmpl
This addresses the invalid_parameter: redirect_uri error from keycloak in production (because keycloak isn't seeing X-Forwarded-Proto, it's expecting the redirect_uri to be http, not https).
> security-filter is what sets X-Forwarded-Proto

- webui/src/Page/Survey.elm
- webui/src/Visualization.elm
Don't show the answer categories during the survey to prevent biasing the responses, and specify the layout order for the facets/categories in the chart.
> Survey polish

- docker-compose.yml
- flyway/sql/V29__alter_files_id.sql
- havenapi/actions/app.go
- havenapi/actions/registration_funnel.go
- havenapi/actions/reports.go
- havenapi/models/file.go
- keycloak/data/havendev-realm.json
- webui/src/Data/Report.elm
- webui/src/Page/Reports.elm
- worker/main.go
@statik  hi!
This PR will create the zip file for the report and also refactor the files table to be more inline with what gobuffalo is looking for since we will use buffalo more in the future. We now use a buffalo download handler instead of the rpc call.
Needs a fix for the duplicate `iss` key in the jwt due to the custom mapper for gatekeeper/keycloak.
Go through the survey and login with the newly created user and download the report. Currently you need to change the custom mapper in keycloak to actually download it due to the duplicate iss key in the jwt. Just modify the Token Claim Name to `issExtra` since it requires a claim name.
> WIP: Create zip and use buffalo for file download handler

- worker/main.go
Faktory jobs require an error to be returned
if it is to retry the job. This portion was not
returning an error properly and not retrying.
> Fix for faulty error return

- webui/src/Page/Survey.elm
There was a bug that was introduced earlier that causes there to be a post right away to surveys/ even if the user was not logged in.
> Fix for posting to surveys all the time

- dc
- dca
- docker-compose.admin.yml
- docker-compose.yml
- postgresql-data/servers.json
New dca helper script makes it easy to run utility containers
like mailhog, pgadmin, plantuml, but does not impose the overhead
of downloading and building all those containers when a developer
just wants to run the webui.
docker-compose up -d will now only start application related containers.
Quick examples of using the utility containers
./dca up -d pgadmin4
./dca run plantuml
pgadmin4 is also preconfigured with the server connection for
postgres, making it more streamlined to connect to the dev
database.
> Split docker-compose, preconfig pgadmin.

- webui/src/Main.elm
- webui/src/Page/Survey.elm
This makes the top part of the page sticky for the questions in the survey, that way when scrolling on mobile the question and the points remaining is always visible.
> Sticky question, better policy loading

- webui/src/Data/Survey.elm
Fixes HAV-268, survey state decoding. Now when partway through a survey and reloading the page, your state is remembered/restored.
> Fix survey state decoding after reload.

- worker/Dockerfile
Fix crash when generating report zip (I introduced a bug when I added the `compilereport` script to the zip file)
> Fix HAV-297 crash when creating report.

- webui/src/Page/Home.elm
- webui/src/Page/Survey.elm
- webui/src/main.scss
A few fixes here and there. 
-Cut down on the amount of white space seen on mobile.
-Implemented thumb image.
-I made the graph on the "finished survey" page a max-width so it fits on mobile better. Possibly too small to read now though?
@statik I noticed you put a fixed height of 170px on the containers "to prevent twitching". I didn't see the commit until just now, and I already deleted that snippet of code because it caused the containers to not line up correctly and they were overlapping a bunch on mobile (landscape mode). I'm not noticing any twitching though, can you let me know if what you saw is back and if so maybe an img so I can see that same thing? Thanks!
> Cleaning up some UI

- webui/elm.json
- webui/src/Main.elm
Survey screens are not yet animated because the
survey page view is implemented differently and
doesn't change the URL. Survey screens need to
be set up to pushState on the URL so that browser
history works (allowing people to go back and
change answer) and we can integrate transitions.
Demo here: https://www.loom.com/share/8117abccfd5146ce876f717a5bb09a88
> Animated transitions between internal pages.

- keycloak-service-providers/magic-link/src/main/java/org/kindlyops/auth/magic/MagicLinkFormAuthenticator.java
- keycloak-service-providers/magic-link/src/main/resources/theme-resources/templates/view-email.ftl
We now inform the user to use the same browser
when generating a magiclink and remind them in
the email as well.
post link creation:
email content:
> Adds magiclink instructions to use same browswer

- gatekeeper/config/gatekeeper.tmpl
With this enabled gatekeeper will inject the
new access token into the request so the user
does not need to do a full page refresh anymore.
Issue #HAV-15
> Fix access token not refreshing automatically

- apitest/features/sqitch-nojwt.feature
- havenapi/actions/registration_funnel.go
- keycloak-service-providers/magic-link/src/main/resources/theme-resources/templates/login-email-only.ftl
- webui/src/Page/Survey.elm
- webui/src/Utils.elm
Issue #HAV-310
Added html5 email verification in the magic link section but since we are not using an actual form for the registration page we will do a simple regex to look for non whitespace before and after an @ symbol which will then allow the user to click the send button.
We also validate in go and return a 422 status code if we do not receive a proper email. 
Magiclink:
Registration:
> Fix for allowing blank and completely bogus emails

- keycloak/themes/haven/login/login.ftl
Issue #HAV-319
Magiclink was failing due to a dead end url
> Fix for magiclink bug

- README.md
- apitest/Dockerfile
- docker-compose.admin.yml
- docker-compose.yml
- e2e-tests-cleanup.sh
- e2e-tests.sh
- havenapi/Dockerfile-hotreload
- webui/cypress/Caddyfile.tmpl
- webui/cypress/integration/login_spec.js
Working on fixing the cypress e2e test, they were incorrectly reporting as passing before.
loading the login page is giving a 400 error, and the error in the keycloak logs is
```
01:47:46,595 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-1) RESTEASY002130: Failed to parse request.: java.lang.IllegalArgumentException: RESTEASY003415: Illegal uri template: ://dev.havengrc.com:80/auth/realms/havendev/protocol/openid-connect/auth
at org.jboss.resteasy.specimpl.R
```
> Better cypress test

- k8s/failpod.yaml
- k8s/gatekeeper-deployment.yaml
- k8s/havenapi-deployment.yaml
- k8s/havenweb-deployment.yaml
- k8s/kube-slack-deployment.yaml
- k8s/kube-slack-roles.yaml
- k8s/sentry-deployment.yaml
- k8s/worker-deployment.yaml
got kube-slack working on openshift to yell at us when pods start failing after a deploy
> K8s sentry, fixes HAV-264

- apitest/features/sqitch-files.feature
- havenapi/actions/reports.go
- havenapi/actions/surveys.go
- havenapi/models/file.go
Fix needed for listing only the current users reports.
Notable changes found on line 73 of havenapi/actions/reports.go to use the view instead.
Some linting changes as well.
Issue #HAV-333
> Fix for listing only users reports

- havenapi/actions/reports.go
- worker/main.go
Downloads were blank due to not using the correct db search path. Also adding some more error handlers and removed the space in the time string for file naming to prevent any issues passing it to the compile report script.
Issue #HAV-334
> Fix for corrupt downloads

- havenapi/actions/reports.go
- havenapi/models/file.go
The previous commit did not fix the issue. This should now find the file in the database to download if its the user_id and file id for the given user.
Issue #HAV-334
> Fix for download issues
